### ISSUE TITLE
Migrate Jibri to Pulseaudio, then scaling doesn't require new instances, just CPU capacity -> Kubernetes

### ISSUE THREAD

**Issue by kpeiruza** [jitsi/jitsi-autoscaler#88]
Hi,

We've been using jibri+pulseaudio in all our streamings & recordings for up to 6 months. So far it has been tested more than 2000 times and every day we have 30+ tests. It simply works better than Alsa.

This made it trivial to scale Jibri on Kubernetes. We're doing it based on CPU consumption so K8s's HPA does the work for us.

We're planning to feed prometheus with Jibri statuses so we can scale it in an even more clean and exact way.

Feel free to share your thoughts and let's team up to get it up and running :-)

PS: you can try kpeiruza/jibri:v12, it has pulseaudio already bundled + a few tweaks at jibri so it launches ffmpeg against pulse instead of Alsa.

**Comment by omazin** [comment]
Hi @kpeiruza, trying to use your jibri + pulseaudio image in my jibri.yml config as follows:
```yaml
version: '3.5'

services:
    jibri:
        image: kpeiruza/jibri:v12
        restart: ${RESTART_POLICY}
        volumes:
            - ${CONFIG}/jibri:/config:Z
            - /dev/shm:/dev/shm
        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
        devices:
            - /dev/snd:/dev/snd
        environment:
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - XMPP_SERVER
            - XMPP_DOMAIN
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_BREWERY_MUC
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_RECORDING_DIR
            - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
            - JIBRI_STRIP_DOMAIN_JID
            - JIBRI_LOGS_DIR
            - DISPLAY=:0
            - TZ
        depends_on:
            - jicofo
        networks:
            meet.jitsi:
networks:
   meet.jitsi:
      external:
         name: custom_jitsi_network
```
But recording is failing. With jitsi/jibri:latest image it works fine. Could you advice on how to find & fix the problem?
